### ISSUE TITLE
php warning 발생 관련

### ISSUE THREAD

**Issue by wookho** [rx-public/rxp_tag_related#4]
이 자료 만드시기 전에 기존 자료를 원하는 위치에 출력되도록 만 수정해서 사용하고 있는데요. 
이 자료오 거의 같은 것 같아 문의 드립니다.

현재 php8에 대비하기 위해 디버그를 켜고 모든 에러를 확인하고 조치하고 있는데 이 자료에서도 워닝이 발생해서 문의 드립니다.

Warning: implode(): Invalid arguments passed
addons/tag_relation/tag_relation.lib.php:38
addons/tag_relation/tag_relation.lib.php:16
addons/tag_relation/tag_relation.addon.php:33
files/cache/addons/pc.php:1862
classes/display/DisplayHandler.class.php:87
classes/module/ModuleHandler.class.php:1163
index.php:52

저희 코드 라인은 조금 차이 날 수 있을 것 같습니다.

**Comment by wookho** [comment]
$addon_info = array();

를 추가해 주니 에러가 없어지네요.

**Comment by wookho** [comment]
아 그리고 
$output = preg_replace_callback($posRegx, getRxpTagRelated, $output);

여기도 

$output = preg_replace_callback($posRegx, 'getRxpTagRelated', $output); 

이렇게 고쳤습니다.

**Comment by wookho** [comment]
$addon_info = array(); 
를 추가해서 에러가 사라져서 해결된 줄 알았더니 연관글 목록이 설정갯수로 제한이 안되고 연관된 글 모두가 출력되어버리는 문제가 생기네요.

**Comment by bjrambo** [comment]
$addon_info가 기본값으로 무슨형식인지 확인하신다음에 배열일경우에만 array()를 선언하는게 맞습니다

그리고 기존의 데이터가 있는지 없는지도 확인안하신 것 같네요..
